# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings  站点设置
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: C.captain | 技术博客
email: junliang0706@126.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to visit my blog, If there is any wrong place, please understand.
  you can email me,@junliang0706@126.com, Let us discuss them together.

  My motto is: All care is learned.

baseurl: "/hjl21.github.io/" # the subpath of your site, e.g. /blog
url: "https://hjl21.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: none
github_username:  hjl21

# User Settings 博主信息 
username: C.captain
user_description: '热爱技术&设计，一切皆技术' #对博主的一些描述 

# Build settings
markdown: kramdown
theme: minima
plugins:
#  - jekyll-feed
  - jemoji
permalink: /:year/:month/:day/:title:output_ext

# Collections
ollections:
  my_collection:
    output: true
    permalink: /:collection/:name

# Links 来加载 menu 导航 
links: 
 - title: 博客主页 
   url: / 
 - title: 关于博主 
   url: /about/ 
 - title: 联系博主 
   url: /contact/ 
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
